substitutions:
  name: jezus-esp
  friendly_name: jezus

packages:
  base: !include ../common/base.yaml
  monitoring: !include ../common/monitoring.yaml

one_wire:
  - platform: gpio
    pin:
      number: GPIO4
    id: x1

sensor:
  - platform: dallas_temp
    name: "temperature"
    update_interval: 30s
    filters:
      - filter_out: NaN

output:
  - platform: gpio
    pin: GPIO21
    id: 'out21'

  - platform: gpio
    pin: GPIO19
    id: 'out19'

  - platform: gpio
    pin: GPIO18
    id: 'out18'

  - platform: gpio
    pin: GPIO5
    id: 'out5'

switch:
  - platform: output
    name: "sprinkler_valve_sw0"
    output: 'out21'
    id: sprinkler_valve_sw0

  - platform: output
    name: "sprinkler_valve_sw1"
    output: 'out19'
    id: sprinkler_valve_sw1

  - platform: output
    name: "sprinkler_valve_sw2"
    output: 'out18'
    id: sprinkler_valve_sw2

  - platform: output
    name: "sprinkler_pump_sw"
    output: 'out5'
    id: sprinkler_pump_sw

sprinkler:
  - id: sprinkler_ctrlr
    main_switch: "Sprinklers"
    auto_advance_switch: "Sprinklers Auto Advance"
    reverse_switch: "Sprinklers Reverse"
    pump_start_pump_delay: 5s
    pump_stop_valve_delay: 3s
    valve_overlap: 5s
    valves:
      - valve_switch: "Section A"
        enable_switch: "Enable Section A"
        pump_switch_id: sprinkler_pump_sw
        run_duration: 900s
        valve_switch_id: sprinkler_valve_sw0

      - valve_switch: "Section B"
        enable_switch: "Enable Section B"
        pump_switch_id: sprinkler_pump_sw
        run_duration: 900s
        valve_switch_id: sprinkler_valve_sw1

      - valve_switch: "Section C"
        enable_switch: "Enable Section C"
        pump_switch_id: sprinkler_pump_sw
        run_duration: 900s
        valve_switch_id: sprinkler_valve_sw2
