substitutions:
  name: squirt-esp
  friendly_name: squirt

packages:
  base: !include ../common/base.yaml
  monitoring: !include ../common/monitoring.yaml

one_wire:
  - platform: gpio
    pin:
      number: GPIO5
    id: x1

sensor:
  - platform: dallas_temp
    name: "temperature"
    update_interval: 30s
    filters:
      - filter_out: NaN

output:
  - platform: gpio
    pin: GPIO02
    id: 'out16'

  - platform: gpio
    pin: GPIO04
    id: 'out17'

  - platform: gpio
    pin: GPIO16
    id: 'out5'

  - platform: gpio
    pin: GPIO17
    id: 'out18'

switch:
  - platform: output
    name: "squirt_01"
    output: 'out16'
    id: squirt_01

  - platform: output
    name: "squirt_02"
    output: 'out17'
    id: squirt_02

  - platform: output
    name: "squirt_03"
    output: 'out5'
    id: squirt_03

  - platform: output
    name: "squirt_04"
    output: 'out18'
    id: squirt_04
