substitutions:
  name: esphome-web-8bc358
  friendly_name: maryja_nie_zawsze_dziewica

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Web server for the ESPHome web interface (graphs, logs, etc.)
web_server:
  port: 80
  include_internal: true
  local: true
  log: true

graph:
  # Bare-minimum auto-ranged graph for Soil Moisture 01
  - id: soil_moisture_graph
    sensor: soil_moisture_01
    duration: 1h
    width: 600
    height: 280
  
  # Multi-trace graph example
  - id: multi_moisture_graph
    duration: 1h
    x_grid: 10min
    y_grid: 1.0     # degC/div
    width: 600
    height: 280
    traces:
      - sensor: soil_moisture_01
        line_type: DOTTED
        continuous: true
        line_thickness: 3
        color: my_blue

# Note: The "display:" section is removed because display output will be provided only on the web interface.

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a Wi-Fi access point for provisioning
  ap: {}

# Captive portal for provisioning Wi-Fi credentials
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Enable Bluetooth LE for provisioning Wi-Fi credentials (only on ESP32)
esp32_improv:
  authorizer: none

sensor:
  - platform: adc
    pin: GPIO36
    name: "Soil Moisture 01"
    update_interval: 1s
    attenuation: 11db
    raw: true
    internal: false
    id: soil_moisture_01

output:
  - platform: gpio
    pin: GPIO21
    id: out21
  - platform: gpio
    pin: GPIO19
    id: out19
  - platform: gpio
    pin: GPIO18
    id: out18
  - platform: gpio
    pin: GPIO5
    id: out5

switch:
  - platform: output
    name: "sw1"
    output: out21
  - platform: output
    name: "sw2"
    output: out19
  - platform: output
    name: "sw3"
    output: out18
  - platform: output
    name: "sw4"
    output: out5

color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%
