substitutions:
  name: mermaid-esp
  friendly_name: mermaid

packages:
  base: !include ../common/base.yaml
  monitoring: !include ../common/monitoring.yaml

output:
  - platform: gpio
    pin: GPIO02
    id: 'out16'

  - platform: gpio
    pin: GPIO04
    id: 'out17'

  - platform: gpio
    pin: GPIO16
    id: 'out5'

  - platform: gpio
    pin: GPIO17
    id: 'out18'

switch:
  - platform: output
    name: "mermaid_01"
    output: 'out16'
    id: mermaid_01

  - platform: output
    name: "mermaid_02"
    output: 'out17'
    id: mermaid_02

  - platform: output
    name: "mermaid_03"
    output: 'out5'
    id: mermaid_03

  - platform: output
    name: "mermaid_04"
    output: 'out18'
    id: mermaid_04
