substitutions:
  name: beczka-esp
  friendly_name: beczka

packages:
  base: !include ../common/base.yaml
  monitoring: !include ../common/monitoring.yaml

# czarny - zasilanie
# niebieski high
# zolty - mid
# czerwony - low
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO21
      mode:
        input: true
        pullup: true
    name: "level_high"
    filters:
      - delayed_on: 10ms

  - platform: gpio
    pin:
      number: GPIO19
      mode:
        input: true
        pullup: true
    name: "level_mid"
    filters:
      - delayed_on: 10ms

  - platform: gpio
    pin:
      number: GPIO18
      mode:
        input: true
        pullup: true
    name: "level_low"
    filters:
      - delayed_on: 10ms
